In [143]:
import numpy as np
import pandas as pd

In [147]:
mat = pd.read_csv("matrix4.csv",header = None)
coef = pd.read_csv("coef4.csv",header = None)
mat1 = np.array(mat)
coef = np.array(coef)
mat1 = mat1.astype(float)
coef = coef.astype(float)
mat = mat1[:,:-1]
ans = mat1[:,-1]
coef = coef[0]
ind = np.array(range(mat.shape[1]-mat.shape[0],mat.shape[1]))
ind = np.array([6,7,9,10,12,13,15,16])

In [148]:
z = np.dot(coef[ind],mat)
dec = coef - z
print(dec)

[ 2200. -2200.   400.  -400.   399.  -100.     0.     0.  -100.     0.
     0.  -100.     0.     0.  -100.     0.     0.]


In [149]:
while max(dec)>0:
    incoming = np.where(dec == max(dec))[0][0]
    divider = (mat[:,incoming])
    divider[divider==0] = 10**-8
    incd = (ans/divider)
    incd[divider<0] = 10**12
    outgoing = np.where(incd == min(incd))[0][0]
    ind[outgoing] = incoming
    ans = ans - min(incd)*mat[:,incoming]
    ans[outgoing] = min(incd)
    mat[outgoing,:]=mat[outgoing,:]/(mat[outgoing,incoming])
    for i in range(mat.shape[0]):
        if i!=outgoing:
            mat[i] = mat[i] - mat[i,incoming]*mat[outgoing]
    z = np.dot(coef[ind],mat)
    print("Mat = ")
    print(pd.DataFrame(mat))
    dec = coef - z
    print("Dec = ")
    print(dec)
    print("ans = ")
    print(ans)
    print("ind = ")
    print(ind)

Mat = 
    0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0  0.0  0.0  0.9 -0.9  0.9 -1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1   
1  0.0  0.0  0.9 -0.9 -1.1  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1   
2  0.0  0.0  0.6 -0.6  0.6  0.0  0.0  0.0 -1.0  1.0  0.0  0.0  0.0  0.0  0.4   
3  0.0  0.0  0.6 -0.6 -1.4  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.4   
4  0.0  0.0  0.3 -0.3  0.3  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  1.0  0.0  0.7   
5  0.0  0.0  0.3 -0.3 -1.7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.7   
6  1.0 -1.0  0.1 -0.1  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.1   
7  0.0  0.0  0.0  0.0 -2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   

    15   16  
0 -0.1  0.0  
1 -0.1  0.0  
2 -0.4  0.0  
3 -0.4  0.0  
4 -0.7  0.0  
5 -0.7  0.0  
6  0.1  0.0  
7 -1.0  1.0  
Dec = 
[   0.    0.  180. -180.  179. -100.    0.    0. -100.    0.    0. -100.
    0.    0.  120. -220.    0.]
ans = 
[1.5 1.5 5.  5.  1.5 1.5 3.

In [150]:
ind

array([ 4,  5, 11, 10, 14, 13,  0,  2])

In [151]:
dec

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.66666669e-09,
        0.00000000e+00,  0.00000000e+00, -1.00000000e+02, -3.33333332e-01,
       -5.00000001e-01, -9.95000000e+01,  0.00000000e+00,  0.00000000e+00,
       -1.00000000e+02,  0.00000000e+00,  0.00000000e+00, -1.00000000e+02,
       -1.66666670e-01])

In [152]:
ans

array([2.00000001, 4.00000004, 2.99999999, 4.00000001, 3.99999998,
       1.00000002, 3.33333332, 3.66666672])

In [125]:
mat.shape

(5, 12)

In [123]:
mat

array([[-1.00000000e-09,  7.22222193e-10,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  4.00000000e-01,
        -1.00000000e-01,  4.44444403e-10,  3.33333302e-10,
         5.55555503e-11, -5.55555581e-11, -1.00000000e-01],
       [-4.44444475e-10, -7.22222230e-01,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  8.44444502e-01,
        -4.44444611e-02, -4.44444456e-01,  6.66666658e-01,
        -5.55555570e-02,  5.55555548e-02, -4.44444611e-02],
       [ 5.33333225e-09,  3.66666632e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.86666680e+00,
         1.53333321e+00,  5.33333283e+00,  3.99999962e+00,
         6.66666604e-01,  3.33333303e-01,  5.33333207e-01],
       [ 1.00000000e+00,  9.99999963e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -4.00000027e-01,
         9.99999967e-02,  9.99999946e-01, -4.03333296e-08,
        -6.72222159e-09, -3.27777745e-09,  9.99999967e-02],
       [ 1.00000000e+00,  0.00000000e+00, -1.0000000